create extension if not exists pgcrypto;
create table if not exists public.profiles(
 id uuid primary key references auth.users(id) on delete cascade,
 name text not null,
 email text unique,
 username text unique not null,
 balance bigint not null default 0,
 referral_code text unique not null,
 role text not null default 'user' check(role in ('user','admin')),
 created_at timestamptz not null default now()
);
create table if not exists public.settings(key text primary key,value text not null);
create table if not exists public.stor_items(
 id bigint generated by default as identity primary key,
 email text not null unique,
 submitted_by uuid not null references public.profiles(id),
 generated_by_admin text,
 status text not null default 'PENDING' check(status in ('PENDING','ACCEPTED','REJECTED')),
 created_at timestamptz not null default now()
);
create table if not exists public.withdrawals(
 id bigint generated by default as identity primary key,
 user_id uuid not null references public.profiles(id),
 amount bigint not null,
 dana_number text not null,
 dana_name text not null,
 status text not null default 'PENDING',
 created_at timestamptz not null default now()
);
create table if not exists public.audit_log(
 id bigint generated by default as identity primary key,
 actor_email text not null,
 action text not null,
 target_email text,
 details text,
 created_at timestamptz not null default now()
);
insert into public.settings(key,value) values
('store_status','OPEN'),('price','3800'),('min_withdrawal','10000'),('txt_pool',''),('tutorial_url',''),('whatsapp_url',''),('telegram_url',''),
('rules','1. STOR hanya alamat email/TXT tanpa password, OTP, cookie, atau kredensial.\n2. Email yang sudah pernah masuk STOR tidak dapat disetor ulang.\n3. Admin dapat mencari email dan melihat pemilik/statusnya.')
on conflict(key) do nothing;

alter table public.profiles enable row level security;
alter table public.settings enable row level security;
alter table public.stor_items enable row level security;
alter table public.withdrawals enable row level security;
alter table public.audit_log enable row level security;

create or replace function public.increment_balance(p_user_id uuid,p_amount bigint)
returns bigint language plpgsql security definer set search_path=public as $$
declare b bigint; begin update profiles set balance=balance+p_amount where id=p_user_id returning balance into b; if b is null then raise exception 'User tidak ditemukan'; end if; return b; end $$;

create or replace function public.create_withdrawal(p_user_id uuid,p_amount bigint,p_dana_number text,p_dana_name text)
returns bigint language plpgsql security definer set search_path=public as $$
declare b bigint; wid bigint; begin select balance into b from profiles where id=p_user_id for update; if b is null then raise exception 'User tidak ditemukan'; end if; if p_amount<=0 or p_amount>b then raise exception 'Saldo tidak cukup'; end if; update profiles set balance=balance-p_amount where id=p_user_id; insert into withdrawals(user_id,amount,dana_number,dana_name) values(p_user_id,p_amount,p_dana_number,p_dana_name) returning id into wid; return wid; end $$;

-- After creating your first account, promote it to admin in SQL:
-- update public.profiles set role='admin' where username='USERNAME_ANDA';
