const crypto=require('crypto');
const { createClient } = require('@supabase/supabase-js');
const url=process.env.SUPABASE_URL;
const anon=process.env.SUPABASE_ANON_KEY;
const service=process.env.SUPABASE_SERVICE_ROLE_KEY;
if(!url||!anon||!service) throw new Error('Supabase environment variables are missing');
const client=createClient(url,anon,{auth:{persistSession:false,autoRefreshToken:false}});
const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});
const settingsDefaults={store_status:'OPEN',price:'3800',min_withdrawal:'10000',txt_pool:'',tutorial_url:'',whatsapp_url:'',telegram_url:'',rules:'1. STOR hanya alamat email/TXT tanpa password, OTP, cookie, atau kredensial.\n2. Email yang sudah pernah masuk STOR tidak dapat disetor ulang.\n3. Admin dapat mencari email dan melihat pemilik/statusnya.'};
function send(res,status,data){return res.status(status).json(data)}
function path(req){return '/'+String(req.query.path||[]).replace(/^\//,'')}
async function getUser(req){const h=req.headers.authorization||'';const token=h.replace(/^Bearer\s+/i,'');if(!token)return null;const {data,error}=await client.auth.getUser(token);if(error||!data.user)return null;const {data:p}=await admin.from('profiles').select('*').eq('id',data.user.id).maybeSingle();if(!p){let username=(data.user.user_metadata?.username||data.user.email?.split('@')[0]||'user').toLowerCase().replace(/[^a-z0-9_]/g,'').slice(0,24)||'user';let n=1;while((await admin.from('profiles').select('id').eq('username',username).maybeSingle()).data)username=(username.slice(0,20)+(++n)).slice(0,24);const {data:created}=await admin.from('profiles').insert({id:data.user.id,name:data.user.user_metadata?.name||username,username,email:data.user.email||null,role:'user',referral_code:'REF-'+crypto.randomUUID().slice(0,8).toUpperCase()}).select('*').single();return {auth:data.user,profile:created};}return {auth:data.user,profile:p}}
async function requireUser(req,res){const u=await getUser(req);if(!u){send(res,401,{error:'Unauthorized'});return null}return u}
async function requireAdmin(req,res){const u=await requireUser(req,res);if(!u)return null;if(u.profile.role!=='admin'){send(res,403,{error:'Admin only'});return null}return u}
async function getSetting(k){const {data}=await admin.from('settings').select('value').eq('key',k).maybeSingle();return data?.value??settingsDefaults[k]??''}
async function setSettings(obj){for(const [k,v] of Object.entries(obj)){if(k in settingsDefaults)await admin.from('settings').upsert({key:k,value:String(v)},{onConflict:'key'});}}
async function audit(actor,action,target,details){await admin.from('audit_log').insert({actor_email:actor,action,target_email:target||null,details:details||null})}
function safe(p,a){return {id:p.id,name:p.name,username:p.username,email:a?.email||null,balance:p.balance,referral_code:p.referral_code}}
function internalEmail(username){return `${username.toLowerCase()}@local.amarstr.invalid`}
function validEmail(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)}
function lines(txt){return [...new Set(String(txt||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map(x=>x.split('|')[0].trim().toLowerCase()))]}
module.exports=async(req,res)=>{
 const p=path(req); try{
  if(p==='/health')return send(res,200,{ok:true,service:'AMAR STR',mode:'vercel-supabase'});
  if(p==='/auth/config')return send(res,200,{supabase_url:url,supabase_anon_key:anon});
  if(p==='/auth/register'&&req.method==='POST'){
   const {name,username,password}=req.body||{};const u=String(username||'').trim().toLowerCase();
   if(!name||!/^[a-z0-9_]{3,24}$/.test(u)||!password||String(password).length<6)return send(res,400,{error:'Nama, username (3-24 karakter) dan password minimal 6 karakter wajib diisi'});
   const exists=await admin.from('profiles').select('id').eq('username',u).maybeSingle();if(exists.data)return send(res,409,{error:'Username sudah digunakan'});
   const {data:newUser,error}=await admin.auth.admin.createUser({email:internalEmail(u),password:String(password),email_confirm:true,user_metadata:{name:String(name).trim(),username:u}});if(error)return send(res,400,{error:error.message});
   const code='REF-'+crypto.randomUUID().slice(0,8).toUpperCase();let {data:prof,error:pe}=await admin.from('profiles').insert({id:newUser.user.id,name:String(name).trim(),username:u,role:'user',referral_code:code}).select('*').single();if(pe){await admin.auth.admin.deleteUser(newUser.user.id);return send(res,400,{error:pe.message});}
   const {data:session,error:se}=await client.auth.signInWithPassword({email:internalEmail(u),password:String(password)});if(se)return send(res,500,{error:se.message});return send(res,200,{token:session.session.access_token,user:safe(prof,newUser.user),isAdmin:false});
  }
  if(p==='/auth/login'&&req.method==='POST'){
   const {username,password}=req.body||{};const u=String(username||'').trim().toLowerCase();const {data:prof}=await admin.from('profiles').select('*').eq('username',u).maybeSingle();if(!prof)return send(res,401,{error:'Username atau password salah'});
   const {data,error}=await client.auth.signInWithPassword({email:internalEmail(u),password:String(password||'')});if(error)return send(res,401,{error:'Username atau password salah'});return send(res,200,{token:data.session.access_token,user:safe(prof,data.user),isAdmin:prof.role==='admin'});
  }
  if(p==='/auth/google'&&req.method==='POST')return send(res,410,{error:'Gunakan tombol Login dengan Google; autentikasi Google sekarang ditangani Supabase Auth.'});
  if(p==='/auth/logout'&&req.method==='POST'){return send(res,200,{ok:true});}
  if(p==='/me'&&req.method==='GET'){const u=await requireUser(req,res);if(!u)return;return send(res,200,{user:safe(u.profile,u.auth),isAdmin:u.profile.role==='admin'});}
  if(p==='/settings/public'&&req.method==='GET'){const keys=['store_status','price','min_withdrawal','tutorial_url','whatsapp_url','telegram_url','rules'];const out={};for(const k of keys)out[k]=await getSetting(k);out.price=Number(out.price||0);out.min_withdrawal=Number(out.min_withdrawal||0);return send(res,200,out);}
  if(p==='/stor'&&req.method==='POST'){const u=await requireUser(req,res);if(!u)return;if(await getSetting('store_status')!=='OPEN')return send(res,400,{error:'STOR sedang ditutup'});const emails=lines(req.body?.txt);if(!emails.length)return send(res,400,{error:'TXT kosong'});const bad=emails.find(e=>!validEmail(e));if(bad)return send(res,400,{error:'Format email tidak valid: '+bad});const added=[],duplicate=[];for(const email of emails){const old=await admin.from('stor_items').select('*,profiles!submitted_by(username)').eq('email',email).maybeSingle();if(old.data){duplicate.push({email,owner:old.data.profiles?.username||'',status:old.data.status});continue;}const ins=await admin.from('stor_items').insert({email,submitted_by:u.profile.id,status:'PENDING'}).select('id').single();if(ins.error){duplicate.push({email,status:'DUPLICATE'});continue}added.push(ins.data.id)}await audit(u.auth.email,'SUBMIT_STOR',u.auth.email,`added=${added.length};duplicate=${duplicate.length}`);return send(res,200,{ok:true,added,duplicate});}
  if(p==='/stor/mine'&&req.method==='GET'){const u=await requireUser(req,res);if(!u)return;const {data,error}=await admin.from('stor_items').select('*').eq('submitted_by',u.profile.id).order('id',{ascending:false});if(error)return send(res,500,{error:error.message});return send(res,200,{items:data||[]});}
  if(p==='/admin/search'&&req.method==='GET'){const u=await requireAdmin(req,res);if(!u)return;const q=String(req.query.q||'').trim();let query=admin.from('stor_items').select('id,email,status,created_at,generated_by_admin,submitted_by,profiles!submitted_by(email,name,balance)').order('id',{ascending:false}).limit(200);if(q)query=query.or(`email.ilike.%${q}%`);const {data,error}=await query;if(error)return send(res,500,{error:error.message});const items=(data||[]).map(x=>({id:x.id,email:x.email,status:x.status,created_at:x.created_at,generated_by_admin:x.generated_by_admin,owner_email:x.profiles?.email,owner_name:x.profiles?.name,balance:x.profiles?.balance}));return send(res,200,{items});}
  if(p.startsWith('/admin/stor/')&&p.endsWith('/status')&&req.method==='POST'){const u=await requireAdmin(req,res);if(!u)return;const id=p.split('/')[3];const status=['PENDING','ACCEPTED','REJECTED'].includes(req.body?.status)?req.body.status:null;if(!status)return send(res,400,{error:'Status invalid'});const {data:row}=await admin.from('stor_items').select('*').eq('id',id).maybeSingle();if(!row)return send(res,404,{error:'STOR tidak ditemukan'});const {error}=await admin.from('stor_items').update({status,generated_by_admin:u.auth.email}).eq('id',id);if(error)return send(res,500,{error:error.message});if(status==='ACCEPTED'&&row.status!=='ACCEPTED'){const price=Number(await getSetting('price')||0);await admin.rpc('increment_balance',{p_user_id:row.submitted_by,p_amount:price});}await audit(u.auth.email,'STOR_STATUS',row.email,`${row.status}->${status}`);return send(res,200,{ok:true});}
  if(p==='/admin/users'&&req.method==='GET'){const u=await requireAdmin(req,res);if(!u)return;const {data,error}=await admin.from('profiles').select('id,name,username,balance,role,created_at').order('id',{ascending:false});if(error)return send(res,500,{error:error.message});return send(res,200,{users:data||[]});}
  if(p.startsWith('/admin/users/')&&p.endsWith('/balance')&&req.method==='POST'){const u=await requireAdmin(req,res);if(!u)return;const id=p.split('/')[3];const amount=Number(req.body?.amount||0);if(!Number.isFinite(amount)||amount===0)return send(res,400,{error:'Nominal tidak valid'});const {data,error}=await admin.rpc('increment_balance',{p_user_id:id,p_amount:amount});if(error)return send(res,400,{error:error.message});const {data:target}=await admin.from('profiles').select('username').eq('id',id).maybeSingle();await audit(u.auth.email,'BALANCE_ADJUST',target?.username||id,String(amount));return send(res,200,{ok:true});}
  if(p==='/admin/settings'&&req.method==='GET'){const u=await requireAdmin(req,res);if(!u)return;const out={};for(const k of Object.keys(settingsDefaults))out[k]=await getSetting(k);return send(res,200,out);}
  if(p==='/admin/settings'&&req.method==='PUT'){const u=await requireAdmin(req,res);if(!u)return;await setSettings(req.body||{});await audit(u.auth.email,'SETTINGS_UPDATE',null,'admin settings updated');return send(res,200,{ok:true});}
  if(p==='/admin/audit'&&req.method==='GET'){const u=await requireAdmin(req,res);if(!u)return;const {data,error}=await admin.from('audit_log').select('*').order('id',{ascending:false}).limit(300);if(error)return send(res,500,{error:error.message});return send(res,200,{items:data||[]});}
  if(p==='/withdraw'&&req.method==='POST'){const u=await requireUser(req,res);if(!u)return;const amount=Number(req.body?.amount||0),min=Number(await getSetting('min_withdrawal')||0);if(amount<min)return send(res,400,{error:`Minimum withdrawal ${min}`});if(amount>Number(u.profile.balance||0))return send(res,400,{error:'Saldo tidak cukup'});const {error}=await admin.rpc('create_withdrawal',{p_user_id:u.profile.id,p_amount:amount,p_dana_number:String(req.body?.danaNumber||''),p_dana_name:String(req.body?.danaName||'')});if(error)return send(res,400,{error:error.message});return send(res,200,{ok:true});}
  return send(res,404,{error:'Not found'});
 }catch(e){console.error(e);return send(res,500,{error:'Server error'})}
}
